apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-resources-api
  namespace: hypertheory
spec:
  selector:
    matchLabels:
      app: learning-resources-api
  template:
    metadata:
      labels:
        app: learning-resources-api
    spec:
      containers:
      - name: learning-resources-api
        image: learningresourceapi:v0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: onCallApiUrl
            value: 'http://oncalldeveloper-service'
          - name: ConnectionStrings__Resources
            value: 'some connection string to an outside database'
